import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable}  h-full antialiased bg-[#ffffff] text-white relative min-h-[100dvh]   overflow-x-hidden`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
